### PR TITLE
Challenges and Awards

### PR DESCRIPTION
**Pull request by alves-luis**
It's the first draft of the page, with undefined prizes. Would like to know your feedback before trying to fill it with more accurate data. What do you think about the structure of the challenges.json?

### CODE REVIEW

**Comment by miguelbrandao** [comment]
I'm liking the overall look, just a few ideas:

- every card should have the same width, with all the content centered (including the description
- what do you think about adding the title "dash-ball-dash" to the cards' titles?
- maybe a little more top and bottom padding in the cards?

**Comment by PedroFerr101** [comment]
For me, so far the json structure looks nice. Probably we will need to add links to the contest statements later on.
What do you think about using a flippable card for each contest ?  On the front it's description and prizes on the back.

**Comment by alves-luis** [comment]
> For me, so far the json structure looks nice. Probably we will need to add links to the contest statements later on.
> What do you think about using a flippable card for each contest ? On the front it's description and prizes on the back.

It's probably cool, but I don't think it's very usable. Besides, it goes against Material UI's guidelines [See more here](https://material.io/components/cards/#behavior)

**Comment by miguelbrandao** [comment]
Yeah, cool but probably not a good idea, it probably wouldn't very intuitive

**Comment by miguelbrandao** [comment]
Can't you make it so that when the are several awards all of them have the same height?

**Pull request merged**
