### PR TITLE
Added How to get there to homepage

### PR DESCRIPTION
**Pull request by alves-luis**
This is a first version. Any suggestions to improve the look? I was thinking about maybe adding transparency to the card content.

_ignore some parts with in-line styling, these will be changed once I'm satisfied with the look_

### CODE REVIEW

**Comment by PedroFerr101** [comment]
What about using a dropdown box to each transportation mean ? Just like the one in speaker's bio. I would also add (or replace) "Como chegar" to the title.

**Comment by nelsonmestevao** [comment]
What if this extense information was in a helper page and here was link a beautiful map of the location with a button to learn more?

**Comment by alves-luis** [comment]
I mean, how many people actually use the information here to get to the event? Don't they just need Altice Forum Braga? And then they use their app of choice to get directions, if they need to.

That being said, I think we could either go with the dropdown Pedro suggested, or just replace it with Altice Forum Braga and a map below (without having an extra page)

**Comment by miguelbrandao** [comment]
> That being said, I think we could either go with the dropdown @PedroFerr101 suggested, or just replace it with Altice Forum Braga and a map below (without having an extra page)

I'm down for the dropdown! The map also sounds like a good idea. I also think this doesn't require and extra page

**Comment by PedroFerr101** [comment]
Maybe reduce the size of the buttons ? So they could fit in one line only.

**Comment by alves-luis** [comment]
> Maybe reduce the size of the buttons ? So they could fit in one line only.

Which buttons? What could fit in one line only?

**Comment by miguelbrandao** [comment]
:rocket:

**Pull request merged**
