### PR TITLE
Remove box shadow from Countdown

### PR DESCRIPTION
**Pull request by nelsonmestevao**

### CODE REVIEW

**Comment by alves-luis** [comment]
Why the change?

**Comment by nelsonmestevao** [comment]
It's a suggestion. I think it looks better.

What do you think? @alves-luis

**Comment by alves-luis** [comment]
I'm not sure, because it goes with the about box below. Maybe just change from Box to Paper?

**Comment by nelsonmestevao** [comment]
> I'm not sure, because it goes with the about box below. Maybe just change from Box to Paper?

Do you mean the "Sobre" section?

**Comment by nelsonmestevao** [comment]
Actually, I don't really like the shadow in the countdown :confused:

**Pull request merged**
