### PR TITLE
Pf/agenda

### PR DESCRIPTION
**Pull request by PedroFerr101**
Add agenda page (slider with agenda's days inside);
Each day consists of 3 types of activities:

- normal activity: single activity
- double activity: 2 parallel activities
- multiple activity: 4 talks and 2 workshops

### CODE REVIEW

**Comment by miguelbrandao** [comment]
The way the speaker is on the other side here here looks a bit funky, I think it would look better if it was on the left with the other ones.

Also, the margins are too large in mobile view 
(image), I think they should be minimal, just enough to not let the arrows touch the screen border.

Speaking of the arrows, I don't like the way they move when the height changes, it's weird when you are trying to move several days. I'd put them in a fixed position at the top, inline with the date and day of the week, like this: 
image

**Comment by alves-luis** [comment]
I agree with the arrows being in a fixed position at the too, near the day of the week.

**Comment by PedroFerr101** [comment]
> The way the speaker is on the other side here here looks a bit funky, I think it would look better if it was on the left with the other ones.
> 
> Also, the margins are too large in mobile view
> (image), I think they should be minimal, just enough to not let the arrows touch the screen border.
> 
> Speaking of the arrows, I don't like the way they move when the height changes, it's weird when you are trying to move several days. I'd put them in a fixed position at the top, inline with the date and day of the week, like this:
> image

To change the speaker side it is only necessary to move his name from the atribute speakersRight to speakerLeft, on the agenda.json.  

Margins on mobile are too wide because I naively replaced a Grid with a box with fixed margins on side. Already fixed this.

I also don't like the way the arrows change their position.  I will try to fix this asap.

**Comment by PedroFerr101** [comment]
Arrows are now fixed at the top

**Comment by alves-luis** [comment]
I love it 👌

**Pull request merged**
