### PR TITLE
Added partners to homepage

### PR DESCRIPTION
**Pull request by alves-luis**
Should I leave the arrows or just rely on the autoplay?

### CODE REVIEW

**Comment by PedroFerr101** [comment]
Maybe remove the arrows and show 2 slides at the same time. Also shorten the logos a little bit.

**Comment by nelsonmestevao** [comment]
Use the correct partners, please 🙏

**Comment by PedroFerr101** [comment]
I think it looks good

**Comment by alves-luis** [comment]
Waiting on the images of all the partners to merge @PedroFerr101 @miguelbrandao

**Comment by miguelbrandao** [comment]
:rocket:

**Pull request merged**
